### PR TITLE
Closes: #1 Updated validations.py python script.

### PR DESCRIPTION
**Pull request by ftmorsun**
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by foralacatag** [comment]
Fixed CLA requirement by updating associated e-mails

**Comment by ftmorsun** [comment]
> @googlebot I signed it!

**Comment by ftmorsun** [comment]
Fixed the behavior of validate_user function in validations.py.

**Review by ftmorsun — COMMENTED** [review]
Fixed the behavior of validate_user function in validations.py.

**Pull request closed without merging**
