### PR TITLE
Closes : #1

### PR DESCRIPTION
**Pull request by seonWKim**
Updated validation.py python script
Fixed the behavior of validate_user function in validation.py

Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by seonwoo960000** [comment]
good job

**Comment by seonwoo960000** [comment]
@googlebot I signed it!

**Comment by mannemhimabindu98** [comment]
Updated validation.py python script.
Fixed the behavior of validate_user function in validation.py.

Fixes #11955 

>It's a good idea to open an issue first for discussion.

 -[] Tests pass
 -[] Appropriate changes to README are included in PR

**Comment by mannemhimabindu98** [comment]
Updated validation.py python script.
Fixed the behavior of validate_user function in validation.py.

Fixes #11955 

>It's a good idea to open an issue first for discussion.

 -[] Tests pass
 -[] Appropriate changes to README are included in PR

**Pull request closed without merging**
