### PR TITLE
Updated validations.py python script

### PR DESCRIPTION
**Pull request by nagarajavg**
Fixed the behavior of validate_user funciton in validations.py
Closes: #1
Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by Kaiyali** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by iamritu** [comment]
fixed the behaviour of validate_user  function in validations.py

**Comment by mathewpeedikayil** [comment]
Updated validations.py python script

**Comment by aguadoeduardo** [comment]
Updated validations.py python script

**Comment by dxhminh** [comment]
fixed the validations.py

**Comment by vishalmankar** [comment]
updated validations.py

**Comment by MihaelaMarina1** [comment]
updated validations.py

**Comment by KarinaJordan92** [comment]
fixed the validations.py

**Comment by dominicmondia** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Fixes #1

**Comment by hassansamini** [comment]
Updating the validations.py
Close:#1

**Comment by SheydaGhb** [comment]
fixed the validation.py

**Comment by ahmad-abdullah44** [comment]
Updating the validations.py
Close: #1

**Comment by josferxcv** [comment]
Updating the Validation.py

**Comment by DEVASSRI** [comment]
Updated validation.py to meet all the criterion of username.
Close: #1

**Comment by theohncom** [comment]
Updated validation.py to meet all the criterion of username.

**Comment by Murthyraju-pydev** [comment]
Fixed user behavior under validations.py script

**Comment by sajuds21** [comment]
Fixed user behavior under validations.py script

**Comment by Victorasuquo** [comment]
fixed the validation script

**Comment by Khally369** [comment]
fixed the validation script

**Comment by MhdIqbalPratama** [comment]
fixed the output

**Comment by anisyasafiraa** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: #31555 
Fixes #31554

**Comment by evertrove** [comment]
Fixed the validation request

**Comment by heykish** [comment]
Fixed the validation request

**Comment by ak-abhilash** [comment]
Updated validations.py python script.

**Comment by huiyinghuan** [comment]
Updated validations.py python script

**Comment by Rikoairlan57** [comment]
Updated validations.py python script

**Comment by Hans2204** [comment]
Updated validations.py python script

**Comment by cmonitt** [comment]
Updated validations.py python script

**Comment by daniyalkhan4413** [comment]
Fixed the validations.py Script and it is now working perfect.

**Comment by kamilanklewicz** [comment]
fixed the validations.py

**Comment by merinof** [comment]
Fixed validations.py

**Comment by Faisal2712** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: #1

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

 Tests pass
 Appropriate changes to README are included in PR

**Comment by 22bayusetia** [comment]
fixed the validations.py

**Comment by reinhardt-s** [comment]
Fixed validations.py

**Comment by danyeka** [comment]
Closes: https://github.com/google/it-cert-automation-practice/issues/1

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

Tests pass
Appropriate changes to README are included in PR

**Comment by JasonHinardi6162001022** [comment]
updated

**Comment by NicoVictorio** [comment]
updated

**Comment by kamilatulgit** [comment]
updated

**Comment by TrisnoPutraRiady** [comment]
joss

**Comment by GaluhAlfisyah** [comment]
gandos jos

**Comment by shakirawlndr** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

Tests pass
Appropriate changes to README are included in PR

**Comment by mr-lunart** [comment]
fixed the validations.py

**Comment by zulfamalika23** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: #1

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

Tests pass
Appropriate changes to README are included in PR

**Comment by ellys15** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

Tests pass
Appropriate changes to README are included in PR

**Comment by joshuagung** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

Tests pass
Appropriate changes to README are included in PR

**Comment by joshuagung** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

Tests pass
Appropriate changes to README are included in PR

**Comment by Nabela8** [comment]
Updated validations.py python script.

**Comment by miptah21** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by azpjago** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1

Fixes #<fixed validations.py>

It's a good idea to open an issue first for discussion.

Tests pass
Appropriate changes to README are included in PR

**Comment by ghifari1** [comment]
update the validation.py

**Comment by miakarisma** [comment]
update validations.py

**Comment by JaimeVC27** [comment]
update validations.py

**Comment by faiqohaisy** [comment]
update validations.py

**Comment by Andana-2612** [comment]
Update validations.py

**Comment by Gourav1997k** [comment]
updated the script

**Comment by MujahidFR** [comment]
Fixed the behavior of validate_user function in validation.py.

**Comment by yayangdimas** [comment]
Closes: #18796 
Updated validations.py python script.

**Comment by terserahm** [comment]
subuh

**Comment by meandmyabsurdlife** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1

Fixes #31128

It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

**Comment by Ilmiu** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by meyyrida35** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

 - [ ] Tests pass
 - [ ] Appropriate changes to README are included in PR

**Comment by edinaalana** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

**Comment by AhyaFajri** [comment]
Closes : #1
Fixes #32243 
Update validations.py python script

**Comment by wiliansyah** [comment]
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by mutiarawptr** [comment]
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by oneraid** [comment]
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by fachrezibayu22** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Review by fachrezibayu22 — COMMENTED** [review]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by Student-rian** [comment]
Fixed the behavior of validate_user funciton in validations.py

**Comment by Student-rian** [comment]
#31128 Fixed the behavior of validate_user funciton in validations.py

**Comment by hanifmfz1312** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py

**Comment by Ghaly19** [comment]
nice

**Comment by RickyIskndrZ** [comment]
Updated validations.py python script

**Comment by Shmebul0ck** [comment]
> Fixed the behavior of validate_user function in validations.py 
Closes: #1 
Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.
 
 * [ ]  Tests pass
 * [ ]  Appropriate changes to README are included in PR

**Comment by rggaptria** [comment]
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by romiptr** [comment]
Fixed the behavior of validate_user function in validations.py
CLOSES: #1

**Comment by PedroCarrinhoRibeiro** [comment]
fixed the validation.py file. Behavior of validate_user function is now correct.
CLOSES: #31128

**Comment by MerlynL** [comment]
Fixed the validation.py file. Behavior of validate_user function is now correct. Closes: https://github.com/google/it-cert-automation-practice/issues/1

**Comment by sandeep026** [comment]
fixes the issue in validation.py
Closes:#1

**Comment by pablo-saborido** [comment]
Fixes validations.py
Closes: #1

**Comment by bapandas5325** [comment]
updating

**Comment by bds16** [comment]
Fixes validations.py

**Comment by NnnnnnD** [comment]
updating validations.py

**Comment by rk636** [comment]
updated validation.py

**Comment by squalla** [comment]
Fixed user behavior under validations.py script

**Comment by abdullah22055** [comment]
Updated

**Comment by abdullah22055** [comment]
Updated validation.py file

**Comment by aenache99** [comment]
Updated validation.py file

**Comment by manuelachamoso** [comment]
Updated validations.py python script

**Comment by erwinpasia** [comment]
Fixed user behavior under validations.py script

**Comment by garimadiyawar** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

 Tests pass
 Appropriate changes to README are included in PR

**Comment by garimadiyawar** [comment]
> Fixed the behavior of validate_user funciton in validations.py Closes: #1 Fixes #<issue_number_goes_here>
> 
> > It's a good idea to open an issue first for discussion.
> 
> * [ ]  Tests pass
> * [ ]  Appropriate changes to README are included in PR

**Comment by garimadiyawar** [comment]
> Fixed the behavior of validate_user funciton in validations.py Closes: #1 Fixes #<issue_number_goes_here>
> 
> > It's a good idea to open an issue first for discussion.
> 
> * [X]  Tests pass
> * [X]  Appropriate changes to README are included in PR

**Comment by garimadiyawar** [comment]
Closes:#32713

**Comment by iribur** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by javierig37** [comment]
Updated validations.py python script

**Comment by wahaj4u** [comment]
Update validations.py python Script

**Comment by Prashant24ei** [comment]
Update validations.py python Script

**Comment by ElTala** [comment]
Fix to validations.py c:

**Comment by Avantikaj-03** [comment]
Fixed the behavior of validate_user funciton in validations.py

**Comment by trangmau** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by roapaula** [comment]
Closes: #1
Updated script of validations.py

**Comment by anaangelicaf** [comment]
Fixel the behavior of validate_user function in validations.py
Closes: # 1

**Comment by ozodbek-sobirjonovich** [comment]
Updated validations.py python script.

**Comment by ozodbek-sobirjonovich** [comment]
Updated validations.py python script.

**Comment by ShahriyorIbragimov** [comment]
Updated validations.py python script.

**Comment by an618** [comment]
Updated validations.py python script.

**Comment by paragmraw** [comment]
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by trongquykid** [comment]
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by audriazasgit** [comment]
fixed the validation script

**Comment by openmind2014** [comment]
Updated validations.py python script.

**Comment by nubitech13** [comment]
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by Jcarletto** [comment]
Fixed the validation.py script

**Comment by robrjon** [comment]
Fixed the validation script but needs review

**Comment by jmlambarri** [comment]
Added validations to prevent usernames begin with '.' or '_'

**Comment by Vladimir0923** [comment]
> Fixed the behavior of validate_user funciton in validations.py Closes: #1 Fixes #<issue_number_goes_here>
> 
> > It's a good idea to open an issue first for discussion.
> 
> * [x]  Tests pass
> * [x]  Appropriate changes to README are included in PR

Suppose this fixes the issues!

**Comment by jormen22** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by A2001ya** [comment]
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by MOgato1** [comment]
Updated validations.py python script. 
Fixed the behavior of validate_user function in validations.py
First time doing something like this so enjoy!

**Comment by akankshauniyal** [comment]
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by hjbrijesh** [comment]
updated validations.py python script
fixed the behavior of the validate_user function in validations.py

**Comment by Shanmugam-velu** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: #31366 

Fixes #<issue_number_goes_here>

its a good idea to open an issue first for disscusion

**Comment by buzasizsu** [comment]
Fixed the behavior of validate_user function in validations.py.

**Comment by logeshwaran003** [comment]
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by Progair** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by MrMarshall3rd** [comment]
fixed the known issue in validations.py

**Comment by AGShapcott** [comment]
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by pathack123** [comment]
fixed the known issue in validations.py

**Comment by Aluxtar** [comment]
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by nervig** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by Mahalavank** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by ahmadabdulnasir** [comment]
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by Shanmugam-velu** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

 Tests pass
 Appropriate changes to README are included in PR

**Comment by PetitEvilGenius** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

Tests pass
Appropriate changes to README are included in PR

**Comment by mcorbelle** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by Nonagis** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

Tests pass
Appropriate changes to README are included in PR

**Comment by Ylindar** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

 Tests pass
 Appropriate changes to README are included in PR

-

**Comment by miansaay** [comment]
Updated validations.py python script.

**Comment by Jabrahamjohn** [comment]
done

**Comment by Emilypzd** [comment]
done

**Comment by neutron220** [comment]
Fixed the behavior of validate_user funciton in validations.py

**Comment by ger1986** [comment]
Updated validations.py python script.

**Comment by echristan** [comment]
testing

**Comment by cohet3** [comment]
xD

**Comment by mathieulinel** [comment]
Fixed the behavior of validate_user funciton in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

 Tests pass
 Appropriate changes to README are included in PR

**Comment by Linhhoang0510** [comment]
Updated the validations.py script

**Comment by YigithanYY** [comment]
Updated the validations.py script

**Comment by jamo6** [comment]
Updated the validations.py script

**Comment by MinhTuDX** [comment]
Done

**Comment by berenbarahir04** [comment]
listo

**Comment by aurca1** [comment]
Fixed the behavior of validate_user function in validations.py
Closes: #1

Fixes on code

It's a good idea to open an issue first for discussion.

Tests pass
Appropriate changes to README are included in PR.

**Comment by AldiPutra24** [comment]
Updated validations.py python script.

**Comment by IrenicCJ** [comment]
Updated validation.py python script

**Comment by mufidmoesz** [comment]
Updated validations.py python script.

**Comment by Zwar11** [comment]
Updated vlidations.py python scripts

**Comment by ariziddannugraha** [comment]
Updated validations.py python script.

**Comment by jekibaringei** [comment]
Updated validations.py python script.

**Comment by lauusz** [comment]
Updated validations.py python script.

**Comment by fransiskusabell** [comment]
Updated validations.py python script.

**Comment by ESPB0808** [comment]
Fixed the behavior of validate_user function in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1

Fixes on code

It's a good idea to open an issue first for discussion.

Tests pass
Appropriate changes to README are included in PR

**Comment by ESPB0808** [comment]
Fixed the behavior of validate_user function in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1

Fixes on code

It's a good idea to open an issue first for discussion.

Tests pass
Appropriate changes to README are included in PR

**Comment by awalul123** [comment]
Fixed the behavior of validations.py python script 
Closes: #1

It's a good idea to open an issue first for discussion about this 

Tests pass
Appropriate changes to README are included in PR

**Comment by lutfiahn00** [comment]
Fixed the behavior of validations.py python script
Closes: https://github.com/google/it-cert-automation-practice/issues/1

It's a good idea to open an issue first for discussion about this

Tests pass
Appropriate changes to README are included in PR

**Comment by RevaRayhan** [comment]
Updated validations.py python script.

**Comment by Darc3d** [comment]
Updated validations.py python script.

**Comment by kelvinlohwy** [comment]
Updated validations.py python script.

**Comment by daniel-lorente** [comment]
Updated validations.py python script.

**Comment by ArtyomSVT** [comment]
I want to add

**Comment by AboJoan** [comment]
I want to add

**Comment by KRS0787** [comment]
Updated validations.py python script.

**Comment by Learner457** [comment]
done

**Comment by applejuiceloverr** [comment]
Updated validations.py python script

**Comment by disizkl** [comment]
updated Validations.py

**Comment by BranislavDurina** [comment]
Updated validations.py python script

**Comment by bumpskir** [comment]
XD

**Comment by Palpk4you** [comment]
update validations.py for username validation

**Comment by Zane-Silabriede** [comment]
Updated validations.py to improve script for username validation.

**Comment by 1989pdip** [comment]
updated fixed the validation.py

**Comment by mspangler582** [comment]
updated validation.py

**Comment by tsaichiaying** [comment]
updated fixed the validation.py

**Comment by Lion07uv** [comment]
'Mise à jour de validations.py

**Comment by laqgit** [comment]
Issues fixed in validation.py

**Comment by foster333** [comment]
Great

**Comment by sp22bscs0058** [comment]
good

**Comment by Codyjoin** [comment]
Updated the validations.py file.

**Comment by 1alorgi** [comment]
Actualización del archivo validacilon.py

**Comment by Ramiro1963** [comment]
Modification on Regular expression included in validations.py python script

**Comment by makhan31568** [comment]
Edited the python Script and corrected

**Comment by Soigeki** [comment]
fixed

**Pull request closed without merging**
