### PR TITLE
Closes: #1

### PR DESCRIPTION
**Pull request by TobiasFrederick**
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by Nilesh12Joshi** [comment]
update

**Comment by sujeetshinde-ss** [comment]
hi

**Comment by rohantangade** [comment]
approved

**Comment by evertrove** [comment]
Updated validations.py python script.

**Comment by tfwinters** [comment]
update to validations.py

**Comment by Rahmanr060902** [comment]
update to validations.py

**Comment by Rahmanr060902** [comment]
Updated validations.py python script.

**Comment by jl-gala** [comment]
Updated validations.py python script.

**Comment by manjuPanjwani** [comment]
Updated Validations.py script
Fixed the User Name Validation. User name can begin with letters only

**Comment by merinof** [comment]
Approved

**Comment by carolhsm** [comment]
updated.

**Comment by Pun197** [comment]
update

**Comment by JimmiEduardSimangunsong** [comment]
update

**Comment by Haseeb2391** [comment]
updated

**Comment by hevadlli** [comment]
updated

**Comment by rifqilhmtfk** [comment]
update

**Comment by hidawns** [comment]
update

**Comment by azpjago** [comment]
Updated validations.py scripts

**Comment by CodeLowfps** [comment]
update

**Comment by khansaduta** [comment]
updated validations.py

**Comment by SAR09** [comment]
update to validations.py

**Comment by JaimeVC27** [comment]
update

**Comment by Gourav1997k** [comment]
Updated

**Comment by Gourav1997k** [comment]
updated the script

**Comment by DarmawanP** [comment]
Updated validations.py

**Comment by kevinhardiansites** [comment]
updated validation.py

**Comment by alipmaskhuri** [comment]
updated validation.py

**Comment by WahyuLuna** [comment]
> Updated validations.py python script. Fixed the behavior of validate_user function in validations.py.
> 
> Fixes #<issue_number_goes_here>
> 
> > It's a good idea to open an issue first for discussion.
> 
> * [ ]  Tests pass
> * [ ]  Appropriate changes to README are included in PR

**Comment by RickyIskndrZ** [comment]
Updated validations.py python script

**Comment by diga-tech** [comment]
updated validation.py

**Comment by abboude1** [comment]
updated validation.py

**Comment by MajesticSeaKraken** [comment]
updated validation.py

**Comment by ll-laila** [comment]
> Updated validations.py python script. Fixed the behavior of validate_user function in validations.py.
> 
> Fixes #<issue_number_goes_here>
> 
> > It's a good idea to open an issue first for discussion.
> 
> * [ ]  Tests pass
> * [ ]  Appropriate changes to README are included in PR

**Comment by pierredec07** [comment]
updated code to not allow users to begin username with forbidden character

**Comment by MoonPatrol007** [comment]
updating validation.py too

**Comment by bapandas5325** [comment]
updating

**Comment by kalmichalis** [comment]
updating

**Comment by Alfia82** [comment]
Updating

**Comment by mdloma** [comment]
Updating

**Comment by mdloma** [comment]
Updating

**Comment by abdullah22055** [comment]
Updated

**Comment by ChetnaMonga** [comment]
hh

**Review by ChetnaMonga — COMMENTED** [review]
welcome

**Comment by abhijeetrana1** [comment]
updatesd

**Comment by garimadiyawar** [comment]
updated

**Comment by garimadiyawar** [comment]
Updated validations.py python script. Fixed the behavior of validate_user function in validations.py.

Fixes #32713

It's a good idea to open an issue first for discussion.

 Tests pass
 Appropriate changes to README are included in PR

**Comment by garimadiyawar** [comment]
> > Updated validations.py python script. Fixed the behavior of validate_user function in validations.py.
> > Fixes #32713
> > > It's a good idea to open an issue first for discussion.
> > 
> > 
> > 
> > * [X]   Tests pass
> > * [X]   Appropriate changes to README are included in PR

**Comment by fillah11** [comment]
updt

**Comment by hariselef** [comment]
Updated validations.py python script. Fixed the behavior of validate_user function in validations.py.

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

 Tests pass
 Appropriate changes to README are included in PR

**Comment by iribur** [comment]
updated validations.py python script.

**Comment by iribur** [comment]
updated

**Comment by hanessn1** [comment]
Updated validations.py python script.

**Comment by wahaj4u** [comment]
update usernames

**Comment by Prashant24ei** [comment]
Updated validations.py python script.

**Comment by Avantikaj-03** [comment]
updated validations.py python script

**Comment by trangmau** [comment]
Updated.

**Comment by anam-f** [comment]
:)

**Comment by madmichelle5** [comment]
updated validations.py python script

**Comment by dlucianop** [comment]
Updated

**Comment by jorgefdc97** [comment]
Updated and approved 👯

**Comment by lewislampkin** [comment]
from GitHub, create a pull request from your forked repository [git-username]/it-cert-automation-practice

**Comment by ozodbek-sobirjonovich** [comment]
Updated validations.py python script.

**Comment by mezaj15** [comment]
updated

**Comment by enikocj** [comment]
Updated validations.py python script.

**Comment by SourBob39** [comment]
Updated validations.py 
Closes: #1

**Comment by ayeshaashaikh** [comment]
updated validations.py python script

**Comment by openmind2014** [comment]
Updated validations.py python script.

**Comment by fmhd-lab** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #1

It's a good idea to open an issue first for discussion.

 Tests pass
 Appropriate changes to README are included in PR

**Comment by sumitpatel25** [comment]
UPDATED validations.py script

**Comment by oscar00v** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes https://github.com/google/it-cert-automation-practice/issues/1

It's a good idea to open an issue first for discussion.

Tests pass
Appropriate changes to README are included in PR

**Comment by Michellebagot** [comment]
updated

**Comment by luca-farinola** [comment]
closed

**Comment by azani-tvlk** [comment]
Fixed the behavior of Validate_user function in Validation.py
Fixes#1

**Comment by aruimy99** [comment]
closed

**Comment by vwederian** [comment]
closed

**Comment by babernatgh** [comment]
Issue closed

**Comment by gnartonwork** [comment]
hi

**Comment by jijunnguyen** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

 - [ ] Tests pass
 - [ ] Appropriate changes to README are included in PR

**Comment by Shanmugam-velu** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #<issue_number_goes_here>

**Comment by pathack123** [comment]
hi

**Comment by Vilicaprogramer** [comment]
updated

**Comment by DarkyAndSparky** [comment]
> Updated validations.py python script. Fixed the behavior of validate_user function in validations.py.
> 
> Fixes #<issue_number_goes_here>
> 
> > It's a good idea to open an issue first for discussion.
> 
> * [ ]  Tests pass
> * [ ]  Appropriate changes to README are included in PR

**Comment by kato1990** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.
Fixes #<issue_number_goes_here>

**Comment by svat-ok** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by DevenSuji** [comment]
Updated the validations.py script.
Also fixed the behavior of validate_user function in validations.py.

**Comment by arshid90** [comment]
3

**Comment by djfarmgirl** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by navratiljiri** [comment]
Updated validations.py python script.

**Comment by Arun-Kumar-Barik** [comment]
Changed

**Comment by CyberMastermind** [comment]
updated

**Comment by HadriSang** [comment]
hi

**Comment by Shanmugam-velu** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

 Tests pass
 Appropriate changes to README are included in PR

**Comment by anjanchowdhury** [comment]
done

**Comment by Romanek5** [comment]
yeap,done it too

**Comment by Mister1993** [comment]
+1

**Comment by Mohamed-Elmanzalawi** [comment]
Done

**Comment by the1collieman** [comment]
Done

**Comment by jgavito1** [comment]
done

**Comment by HARSH-PRANJAL** [comment]
updated the if else statement

**Comment by nadia-klm** [comment]
done

**Comment by alexisearl14** [comment]
Closes: #1

**Comment by agusmastan** [comment]
Approved.

**Comment by miansaay** [comment]
Closes: #1

**Comment by wowAamazing** [comment]
Closes #1
Let's hope that no one will have to fix it again after this.

**Comment by Mimishu77** [comment]
It's Ok.

**Review by tliu-mcan — COMMENTED** [review]
Review

**Comment by tliu-mcan** [comment]
Not the same as the instruction.

**Comment by sugunabarathi** [comment]
finished as per instruction

**Comment by readysetlearn** [comment]
Closes: #1

**Comment by ashif-git** [comment]
Completed.

**Comment by Jabrahamjohn** [comment]
closed

**Comment by ZzHotte** [comment]
Closed

**Comment by 22vish04** [comment]
closes #10747 
update and fixed issue

**Comment by cohet3** [comment]
ya esta no?¿

**Comment by Sankalpa7** [comment]
update and fixed

**Comment by RamsesVillegas** [comment]
update to validations.py

**Comment by LarrySu508** [comment]
updated validations.py python script

**Comment by The-nurvy** [comment]
lets do it

**Comment by jairo-andres-a-m** [comment]
Hi, updating validation behavior

**Comment by jamo6** [comment]
Updated validation.py behavior

**Comment by zeinware** [comment]
Updated validation.py python script

**Comment by Shruthi489** [comment]
Fixed the behavior of validate_user function in validations.py

**Comment by Girlpower2024** [comment]
done

**Comment by PFKimmerle** [comment]
Fixed the behavior of validate_user function in validations.py

**Comment by jekibaringei** [comment]
done

**Comment by Ramadhanul** [comment]
Done update validation.py

**Comment by awalul123** [comment]
done update

**Comment by a2rey** [comment]
Fixed behavior of validate_user function in validations.py
Closes: #1

**Comment by GoodDevz** [comment]
Fixed behavior of validate_user function in validations.py
Closes: https://github.com/google/it-cert-automation-practice/issues/1

**Comment by kelvinlohwy** [comment]
Fixed behavior of validate_user function in validations.py
Closes: #1

**Comment by abbos77** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by lmf80** [comment]
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by fac10r** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by sediqa01** [comment]
> Updated validations.py python script. Fixed the behavior of validate_user function in validations.py.
> 
> Fixes #the behavior of the validate_user function in validations.py.

**Comment by AboJoan** [comment]
#Updated validations.py python script. Fixed the behavior of validate_user function in validations.py.
Fixes #the behavior of the validate_user function in validations.py.

**Comment by phenixsam** [comment]
hi

**Comment by cuba6112** [comment]
#Updated validations.py python script. Fixed the behavior of validate_user function in validations.py.
Fixes #the behavior of the validate_user function in validations.py.

**Comment by gerrowneyVB** [comment]
Done

**Comment by vahekhumaryan** [comment]
as assigned

**Comment by bitsByB** [comment]
Update validations.py python script.
Fix the behavior or validate_user function by modifying regex.

Fixes #31366 

- [ ] Test passes
- [ ] Appropriate changes to validations.py are included in PR

Thanks :)

**Comment by Shachin97** [comment]
cLose#1

**Comment by ghost** [comment]
Updated validations.py  script.

**Comment by piechnik-d** [comment]
Proposed change Summary: test username for illegal character in the first position.
End of changes.

**Comment by heinyman317** [comment]
Updated validations.py script @Gebreyesus-Kidanu-2

**Comment by jeypeee** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of the validate_user function in validations.py.

**Comment by jeypeee** [comment]
Updated validations.py script.

**Comment by lagarlabs** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #1 error


 Tests pass
 Appropriate changes to README are included in PR

**Comment by simpleReno** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by Naisha31** [comment]
Updated validations.py

**Comment by Jepkosgei3** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by DaveEvan** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #1

**Comment by katronitram** [comment]
updated validations.py

**Comment by sengal67** [comment]
Updated validations.py python script

**Comment by Learner457** [comment]
updated validations.py 
thanks coursera

**Comment by bickramjitbasu09** [comment]
updated validations.py

**Comment by applejuiceloverr** [comment]
Updated validations.py python script.

**Comment by apardalak** [comment]
updated validations.py
thanks coursera

**Comment by ergastirio15** [comment]
updated validations.py script.

**Comment by ChasTheSimorgh** [comment]
updated validations.py script

**Comment by nabilalmiklafy** [comment]
update file pull req

**Comment by Keya0311** [comment]
updated validations.py script

**Comment by satyajit5007** [comment]
Updated validations.py python script.

Fixed the behavior of validate_user function in validations.py.

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

 Tests pass
 Appropriate changes to README are included in PR

**Comment by jaspers91** [comment]
update and fix the problem.

**Comment by BranislavDurina** [comment]
up

**Comment by jatin072** [comment]
Fixed validations.py script

**Comment by bumpskir** [comment]
I fixed git, it was broken before I pushed and pulled git.

**Comment by Palpk4you** [comment]
fix the validations.py script to check username should start with alphabets only

**Comment by Deepika27387** [comment]
Updated the validation file to ensure the user name starts with alphabets only

**Comment by celjpooh** [comment]
Fixed the behavior of validate_user function in validations.py.

**Comment by kenhuang55** [comment]
Validation file updated to only start with alphabetical characters

**Comment by tresper** [comment]
schatzi was here

**Comment by sonikhatri1991** [comment]
Updated validations.py python script.

**Comment by CasandraToler** [comment]
updated the validations.py script

**Comment by smoky1126** [comment]
updated the validations.py script

**Comment by Elmar026** [comment]
Updated validations.py python script.

**Comment by Jaldabaoth1982** [comment]
Add the first character validation

**Comment by scrawnny1999** [comment]
updated validations.py

**Comment by Shawn-le-don-epic** [comment]
Successfully updated validations.py and now the script checks if the username begins with a letter or not.

**Comment by cgalvaojr1976** [comment]
current issue #1

**Comment by cgalvaojr1976** [comment]
Successfully updated validations.py

**Comment by Muriber** [comment]
Updated validations.py python script.

**Comment by FadouaBouchrite** [comment]
done

**Comment by cagalli746** [comment]
done.

**Comment by kingprofire** [comment]
updated

**Comment by AlbertoGaya** [comment]
update

**Comment by Casey-Redden** [comment]
updated!

**Comment by Jay-7** [comment]
Updated.

**Comment by mbolano42** [comment]
Updated!

**Comment by KritarthaBarman0101** [comment]
Updated.

**Comment by Aldup** [comment]
updated successfully

**Comment by DodoJota** [comment]
Update done!

**Comment by yfa9** [comment]
updated

**Comment by Beeditor04** [comment]
nice

**Comment by foster333** [comment]
Nice

**Comment by HsAhRaSrHmIaT** [comment]
Updated

**Comment by denvars** [comment]
Modifications on validation.py

**Comment by Anas-abahaj** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by Eduardolans** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

- [x]  Tests pass
- [x]  Appropriate changes to README are included in PR

**Comment by RukiaHinds** [comment]
Updated

**Comment by jiseop-byeon** [comment]
Updated validations.py python script.

**Comment by smartinez100** [comment]
Updated validations.py

**Comment by jemcuser** [comment]
Updated validations.py

**Comment by fm2077** [comment]
Corrected validations.py

**Comment by Harras-elmehdi** [comment]
corrected validation

**Comment by simonsommer86** [comment]
Corrected

**Comment by ilyassajd** [comment]
valid

**Comment by penasaran** [comment]
Remove bugs from validations.py modul.
:)

**Comment by zeeps1991** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

[ ] Tests pass
[ ] Appropriate changes to README are included in PR

**Comment by gulugulubing** [comment]
Updated the validations.py file.

**Comment by JuanAIE** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

 - [ ] Tests pass
 - [ ] Appropriate changes to README are included in PR

**Comment by YuHsin-Chang** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

 Tests pass
 Appropriate changes to README are included in PR

**Comment by ImAsu1304** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py

Fixes #<issue_number_goes_here>

>It's a good idea to open an issue first for discussion.

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

**Comment by ValentynaDM** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by Rachel-LF** [comment]
Closes: #1 
Updated validations.py python script. Fixed the behavior of validate_user function in validations.py.

**Comment by NoomJesXDev** [comment]
Updated validations.py

**Comment by Tausif321** [comment]
Made changes to validations.py 

Closes: #1

Updated validations.py python script.

Fixed the behavior of validate_user function in validations.py.

**Comment by sagagame0914** [comment]
updated

**Comment by dxvid-moreno** [comment]
The Python script validations.py has now been updated.

**Comment by piggy2011** [comment]
Closes: #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by Emmacyyong** [comment]
Closes: https://github.com/google/it-cert-automation-practice/issues/1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by KIRTAN294** [comment]
Updated

**Comment by Andilemk** [comment]
Updated validations.py script to add test case to check if first character of username is a letter

**Comment by nexiblee** [comment]
Updated

**Comment by amiller2020** [comment]
Updated validations.py script to add test case to check if first character of username is a letter.

**Comment by Nithish-o7** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #<issue_number_goes_here>

It's a good idea to open an issue first for discussion.

[ ] Tests pass
[ ] Appropriate changes to README are included in PR

**Comment by oseiyaw** [comment]
Fixed validations.py. The program now checks to see if the first letter is indeed a letter.

**Comment by Izznpower** [comment]
So we cannot actually pull request? I'm confused.

**Comment by ScholarRinker** [comment]
Updated validations.py

**Comment by truongnamanh** [comment]
Updated validations.py

**Comment by FabHer74** [comment]
update validation

**Comment by teedger** [comment]
Update validations.py

**Comment by mmubashirdev** [comment]
Closes #1
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by obirimelvin** [comment]
updated regex first character is a letter

**Comment by ksingla1885** [comment]
everything up to date

**Comment by n23015330** [comment]
Pull-request

**Comment by kibitzer** [comment]
Updated validations.py so that usernames beginning with an underscore or dot (period) are rejected.

[] Run tests
[] Construct reactor
[] Initiate meltdown

**Comment by rahmatullahh92004-wq** [comment]
done

**Comment by Soigeki** [comment]
done

**Comment by JoejoeSal** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

**Comment by jaykrishnan1997-eng** [comment]
Updated validation.py scrip.

**Comment by amitdas678** [comment]
update validation.py scrip

**Comment by ayushyoyo** [comment]
update validations.py python script

**Comment by Khant-SoDOpe** [comment]
s

**Comment by RomanGSmith** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #1

**Comment by rlaws1** [comment]
Updated validations.py python script.
Fixed the behavior of validate_user function in validations.py.

Fixes #1

**Pull request closed without merging**
